name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.5.0

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm -r install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_PACKAGES }}

      - name: Build
        run: pnpm -r build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: pnpm publish:ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Slack Notification
        if: steps.changesets.outputs.published == 'true'
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": "New RediRedi modules version published",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: Successful deploy completed on run *#${{ github.run_number }}*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n`${{ github.repository }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Pull Request:*\n<${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}|#${{ github.event.number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit Hash:*\n`${{ env.GITHUB_SHA_SHORT }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Message:*\n_${{ github.event.pull_request.title }}_"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "```${{ steps.changesets.outputs.publishedPackages }}```"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "Open Pipeline"
                      },
                      "style": "primary",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYS_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
